## Numpy Arrays and Their Properties

**What is a Numpy?** *A library for numerical computing in python, which provides support for arrays, matrices, and many mathematical functions.*

**Why Numpy?** *It provides high performance, supports multi-dimentional arrays, and works seamlessly with other libraries like pandas and sciki-learn*



**Installing Numpy**
```
pip install numpy
```



In [2]:
import numpy as np

**Creating Numpy Arrays**
- !D Array

In [8]:
arr1 = np.array([1,2,3,4])

- 2D Array

In [9]:
arr2 = np.array([[1,2],[3,4]])

- 3D Array

In [10]:
arr3 = np.array([[[1], [2], [3], [4]]])

**Array Properties**

- Shape: The dimensions of the Array

In [11]:
arr1.shape

(4,)

*1D Array Shape Represents the number of elements in the array*

In [12]:
arr2.shape

(2, 2)

*2D Array is essentially matrix where data is organized in rows and cols*

In [13]:
arr3.shape

(1, 4, 1)

*3D Array can be thought of as a collection of 2D matrices stacked together.*
- The First Represents, The number of 2D matrices, The second represents, The number of rows in each matrix, and the third represents the number of columns in each row

**Dimensions**: The number of axes

In [14]:
arr1.ndim

1

In [15]:
arr2.ndim

2

In [16]:
arr3.ndim

3

**Size**: Total number of elements

In [17]:
arr1.size

4

In [18]:
arr2.size

4

In [19]:
arr3.size

4

**Data Type**: Type of elements

In [20]:
arr1.dtype

dtype('int32')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
arr3.dtype

dtype('int32')

**Array Operations**

**Arthmetic Operations**
- *Operations like addition, subtraction, multiplication, and division can be done element-wise*

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
sum_arr = arr1 + arr2
mul_arr = arr1 * arr2
sub_arr = arr2-arr1
div_arr = arr2//arr1
print(sum_arr, mul_arr, sub_arr, div_arr)

[5 7 9] [ 4 10 18] [3 3 3] [4 2 2]


**Universal Functions (ufuncs)**
- *Functions that operate element-wise on arrays*


In [29]:
np.sin(arr1)

array([0.84147098, 0.90929743, 0.14112001])

In [30]:
np.exp(arr1) #Expotential of each element

array([ 2.71828183,  7.3890561 , 20.08553692])

**Aggregation Functions**
- *Functions like sum, mean, median, etc.*

In [32]:
np.sum(arr3)

10

In [33]:
np.mean(arr3)

2.5

In [34]:
np.std(arr3)

1.118033988749895

**Indexing, Slicing and Iterating**

1. **Indexing**
- *Accessing elements via index*

In [37]:
arr1[0]

1

In [38]:
arr3[0]

array([[1],
       [2],
       [3],
       [4]])

2. **Slicing**
- *Extracting sub arrays*

In [39]:
arr1[1:4]

array([2, 3])

In [56]:
arr1[::-1]

array([3, 2, 1])

In [55]:
arr3[::-1]

array([[[1],
        [2],
        [3],
        [4]]])

**Iterating Over Arrays**

In [58]:
for elem in arr1:
    print(elem)

1
2
3


**Modifying array values**

In [81]:
arr = np.array([1,2,3])
arr[0] = 10
print(arr)

[10  2  3]


**Spliting Arrays**

In [82]:
arr = np.array([1,2,3,4,5,6,7,8,9])
split_arr = np.split(arr,3)
print(split_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


**Resizing Arrays**

In [83]:
arr = np.array([1,2,3,4])
resized_arr = np.resize(arr, (2,3))
print(resized_arr)

[[1 2 3]
 [4 1 2]]


**Boolean Indexing**

In [84]:
arr = np.array([1,2,3,4,5])
filtered_arr = arr[arr>3]
print(filtered_arr)

[4 5]


**Reshaping and Manipulating Arrays**
- *Reshaping and manipulating arrays are essential operations in NumPy to efficiently work with multi-dimensional data. These operations are crucial in various tasks, such as data preparation, Machine learning, Image Processing, and more.*

1. **Reshaping Arrays**

*Reshaping refers to changing the dimension of an array without altering its data. It is useful when you need to transform data for various mathematical or data processing operations.*

In [62]:
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape((2,3)) #Reshape to 2 rows and 3 columns
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


2. **Flattening Arrays**

*Flattening refers to converting a multi-dimensional arrays into a 1D array. This can be useful for feeding data into algorithms or functions that expect a 1D input.*

In [64]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened_arr = arr_2d.flatten()
print(flattened_arr)

[1 2 3 4 5 6 7 8 9]


3. **Reshaping and Manipulating 3D Arrays**
   
*You can also reshape 3D arrays into 2D or 1D arrays, depending on your need. This is useful in tasks like flattening image data, reshaping a tensor for neural networks input, etc.*

In [66]:
arr_3d = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
reshaped_2d = arr_3d.reshape(4,2) #Flatten 3D into 2D
print(reshaped_2d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**Stacking and Splitting Arrays**

- **Vertical Stack**: *Combine arrays row-wise*

In [67]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

- **Horizontal Stack**: *Combine arrays column-wise*

In [68]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

**Advanced Numpy Topics**

**BroadCasting**

*Boradcasting allows NumPy to perform element-wise operations on arrays of different shapes.*

In [70]:
arr1 = np.array([1,2,3])
arr2 = np.array([4])
arr3 = arr1 + arr2
print(arr3)

[5 6 7]


**Linear Algebra Operations**

**Matrix Multiplication**

In [73]:
arr1 = [1,2,3]
arr2 = [4,5,6]

In [74]:
np.dot(arr1, arr2)

32

**Determinent**

In [79]:
arr_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [80]:
np.linalg.det(arr_2d)

0.0

**Vectorization**

*Vectorization refers to the process of performing operations on entire arrays without using explicit loops. By using vectorized operations, You can leverage highly optimized c-based implementations, which can lead to significant performance improvements.*

*In Numpy, operations are automatically vectorized, meaning they apply the operation to the entire array element-wise.*

1. Vectorized operations example
- Add two arrays element-wise without using loops

In [86]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = arr1 + arr2 #The operation arr1 + arr2 is automatically applied element-wise to both arrays.
print(result)

[5 7 9]
